name: artifacts_1
on: 
    push:
        branches: main
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: print message1
              run: echo "hello-1"
    job2:
        needs: job1
        runs-on: ubuntu-latest  
        steps: 
            - name: print message 2
              run: echo "hello-2"
    job3:
        needs: job2
        runs-on: ubuntu-latest
        steps:
              - run: echo "hello-3"
              - run: mkdir -p path/to/artifact
              - run: echo hello > path/to/artifact/world.txt
              - uses: actions/upload-artifact@v4 
                with: 
                   name: my-artifact
                   path: path/to/artifact/world.txt  
