name: fourth-workflow
on: workflow_dispatch
jobs:
    job: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout this repository
              uses: actions/checkout@v4
            - name: installing a version of Python
              uses: actions/setup-python@v5
              with: 
                python-version: '3.10'
            - name: check mkdocs pre-requirements
              run: |
                python --version
                pip --version
            - name: install mkdocs and check the versions
              run: |
                pip install mkdocs
                pip install mkdocs-material
                # check mkdocs is installed
                mkdocs --version
                pip list 