name: upload_artifacts
on: 
    push:
        branches: main
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps: 
            - name: create directories and files
              run: |
                echo "uploading.."
                mkdir one/two/three
                echo "Vishwanathan" > one/two/three/name.txt
                echo "India" > one/two/three/country.txt
            - name: upload all artifacts             
              uses: actions/upload-artifact@v4
              with:
                name: disp-files
                path: one/two/three/

