name: artifacts_1
on: 
    push:
        branches: main
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: print message1
              run: echo "hello-1"
    job2:
        needs: job1
        runs-on: ubuntu-latest  
        steps: 
            - name: print message 2
              run: echo "hello-2"
    job3:
        needs: job2
        runs-on: ubuntu-latest
        steps:
            - name: print message 3
              run: echo "hello-3"

